In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ["Sushil","Roshan","Lucifer","Devil"],
    "marks" : [99.98 , 100, 98 , 88.98],
    "city" : ["Buldhana","Heven","Hell","Hell"]
}

In [3]:
df = pd.DataFrame(dict1)
df

      name   marks      city
0   Sushil   99.98  Buldhana
1   Roshan  100.00     Heven
2  Lucifer   98.00      Hell
3    Devil   88.98      Hell

In [4]:
df.to_csv("friends.csv")

In [5]:
df.to_csv("friends_index_false.csv",index=False)

In [6]:
df.head(2)

     name   marks      city
0  Sushil   99.98  Buldhana
1  Roshan  100.00     Heven

In [7]:
df.tail(2)

      name  marks  city
2  Lucifer  98.00  Hell
3    Devil  88.98  Hell

In [8]:
df.describe()

            marks
count    4.000000
mean    96.740000
std      5.257705
min     88.980000
25%     95.745000
50%     98.990000
75%     99.985000
max    100.000000

In [9]:
train = pd.read_csv("train_speed.csv")
train

   train no.  Speed     city
0       2468     80  Buldana
1       2466     65   mumbai
2       4547     45    dubai
3       2589     78   nagpur

In [10]:
train['Speed'][0] = 100
train

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19780\3581880329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['Speed'][0] = 100

   train no.  Speed     city
0       2468    100  Buldana
1       2466     65   mumbai
2       4547     45    dubai
3       2589     78   nagpur

In [11]:
train.to_csv("new_train_speed.csv")
train

   train no.  Speed     city
0       2468    100  Buldana
1       2466     65   mumbai
2       4547     45    dubai
3       2589     78   nagpur

In [12]:
train.index = ['first','second','third','forth']
train

        train no.  Speed     city
first        2468    100  Buldana
second       2466     65   mumbai
third        4547     45    dubai
forth        2589     78   nagpur

In [13]:
type(train)

pandas.core.frame.DataFrame

In [14]:
train.index = np.arange(1,5)
train

   train no.  Speed     city
1       2468    100  Buldana
2       2466     65   mumbai
3       4547     45    dubai
4       2589     78   nagpur

In [15]:
ser = pd.Series(np.random.rand(34))
ser

0     0.025320
1     0.733833
2     0.061036
3     0.157432
4     0.470054
5     0.480111
6     0.551875
7     0.964843
8     0.822518
9     0.477634
10    0.759902
11    0.759541
12    0.289742
13    0.720616
14    0.385646
15    0.108921
16    0.581742
17    0.984374
18    0.345766
19    0.878451
20    0.561107
21    0.458025
22    0.710418
23    0.739555
24    0.703010
25    0.977880
26    0.645783
27    0.440518
28    0.613639
29    0.110174
30    0.985572
31    0.950650
32    0.842512
33    0.493952
dtype: float64

In [16]:
type(ser)

pandas.core.series.Series

In [17]:
new_pd = pd.DataFrame(np.random.rand(341,5),index=np.arange(341))
new_pd.head()

          0         1         2         3         4
0  0.940535  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3  0.884190  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [18]:
type(new_pd)

pandas.core.frame.DataFrame

In [19]:
new_pd.describe()

                0           1           2           3           4
count  341.000000  341.000000  341.000000  341.000000  341.000000
mean     0.506850    0.495885    0.489276    0.472354    0.500609
std      0.292451    0.292759    0.280938    0.286143    0.290324
min      0.004539    0.004495    0.004712    0.000108    0.000984
25%      0.257642    0.246035    0.257256    0.217642    0.258985
50%      0.525469    0.491696    0.493745    0.469671    0.502543
75%      0.746034    0.760749    0.722975    0.703132    0.746133
max      0.994711    0.998795    0.998365    0.995942    0.998616

In [20]:
new_pd.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
new_pd[0][0] = "Lucifer"

In [22]:
new_pd.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [23]:
new_pd.head()

          0         1         2         3         4
0   Lucifer  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [24]:
new_pd.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            331, 332, 333, 334, 335, 336, 337, 338, 339, 340],
           dtype='int64', length=341)

In [25]:
new_pd.columns

RangeIndex(start=0, stop=5, step=1)

In [26]:
new_pd.to_numpy()

array([['Lucifer', 0.7509742276804094, 0.10980993276171924,
        0.28487658653457404, 0.24931935605039746],
       [0.22720735457809604, 0.6238224790306198, 0.6048586063009358,
        0.27127898549702556, 0.048136634804503364],
       [0.3161925582057409, 0.959645364517634, 0.793529419553301,
        0.3814589887288312, 0.24761608221570042],
       ...,
       [0.0669557520864068, 0.418103912718389, 0.8078535834512776,
        0.5169670127345717, 0.16180798071927383],
       [0.6484422164164463, 0.9177264524302251, 0.3625296581381783,
        0.4721154584602446, 0.33325031209447475],
       [0.3959415759417624, 0.2861543943418864, 0.22520120418844303,
        0.7967381380558893, 0.10338072305100499]], dtype=object)

In [27]:
new_pd[0][0] = 80
new_pd

            0         1         2         3         4
0          80  0.750974  0.109810  0.284877  0.249319
1    0.227207  0.623822  0.604859  0.271279  0.048137
2    0.316193  0.959645  0.793529  0.381459  0.247616
3     0.88419  0.242041  0.354690  0.910700  0.881608
4    0.181373  0.565818  0.765258  0.486793  0.556033
..        ...       ...       ...       ...       ...
336  0.229567  0.560952  0.601893  0.405042  0.352048
337  0.792553  0.251601  0.667149  0.846669  0.199375
338  0.066956  0.418104  0.807854  0.516967  0.161808
339  0.648442  0.917726  0.362530  0.472115  0.333250
340  0.395942  0.286154  0.225201  0.796738  0.103381

[341 rows x 5 columns]

In [28]:
new_pd.to_numpy()

array([[80, 0.7509742276804094, 0.10980993276171924, 0.28487658653457404,
        0.24931935605039746],
       [0.22720735457809604, 0.6238224790306198, 0.6048586063009358,
        0.27127898549702556, 0.048136634804503364],
       [0.3161925582057409, 0.959645364517634, 0.793529419553301,
        0.3814589887288312, 0.24761608221570042],
       ...,
       [0.0669557520864068, 0.418103912718389, 0.8078535834512776,
        0.5169670127345717, 0.16180798071927383],
       [0.6484422164164463, 0.9177264524302251, 0.3625296581381783,
        0.4721154584602446, 0.33325031209447475],
       [0.3959415759417624, 0.2861543943418864, 0.22520120418844303,
        0.7967381380558893, 0.10338072305100499]], dtype=object)

In [29]:
new_pd.head()

          0         1         2         3         4
0        80  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [30]:
new_pd.sort_index(axis=1)

            0         1         2         3         4
0          80  0.750974  0.109810  0.284877  0.249319
1    0.227207  0.623822  0.604859  0.271279  0.048137
2    0.316193  0.959645  0.793529  0.381459  0.247616
3     0.88419  0.242041  0.354690  0.910700  0.881608
4    0.181373  0.565818  0.765258  0.486793  0.556033
..        ...       ...       ...       ...       ...
336  0.229567  0.560952  0.601893  0.405042  0.352048
337  0.792553  0.251601  0.667149  0.846669  0.199375
338  0.066956  0.418104  0.807854  0.516967  0.161808
339  0.648442  0.917726  0.362530  0.472115  0.333250
340  0.395942  0.286154  0.225201  0.796738  0.103381

[341 rows x 5 columns]

In [31]:
new_pd.sort_index(axis=1 , ascending=False)

            4         3         2         1         0
0    0.249319  0.284877  0.109810  0.750974        80
1    0.048137  0.271279  0.604859  0.623822  0.227207
2    0.247616  0.381459  0.793529  0.959645  0.316193
3    0.881608  0.910700  0.354690  0.242041   0.88419
4    0.556033  0.486793  0.765258  0.565818  0.181373
..        ...       ...       ...       ...       ...
336  0.352048  0.405042  0.601893  0.560952  0.229567
337  0.199375  0.846669  0.667149  0.251601  0.792553
338  0.161808  0.516967  0.807854  0.418104  0.066956
339  0.333250  0.472115  0.362530  0.917726  0.648442
340  0.103381  0.796738  0.225201  0.286154  0.395942

[341 rows x 5 columns]

In [32]:
new_pd.head()

          0         1         2         3         4
0        80  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [33]:
type(new_pd[0])

pandas.core.series.Series

In [34]:
new_pd.columns = list("ABCDE")

In [35]:
new_pd.head()

          A         B         C         D         E
0        80  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [36]:
new_pd.loc[0,'A'] = 454
new_pd.head()

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [37]:
newpd = new_pd.drop('E',axis=1)
newpd.head()

          A         B         C         D
0       454  0.750974  0.109810  0.284877
1  0.227207  0.623822  0.604859  0.271279
2  0.316193  0.959645  0.793529  0.381459
3   0.88419  0.242041  0.354690  0.910700
4  0.181373  0.565818  0.765258  0.486793

In [38]:
newpd.loc[[1,2],['C','D']]

          C         D
1  0.604859  0.271279
2  0.793529  0.381459

In [39]:
new_pd.head()

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [40]:
new_pd.loc[[1,2]]

          A         B         C         D         E
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616

In [41]:
new_pd.loc[[1,2],:]

          A         B         C         D         E
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616

In [42]:
new_pd.loc[(new_pd['A'] < 0.3) & (new_pd['C'] > 0.1) ]
# how many Rows in A column is less than 0.3
# and how many Rows in C column is greater than 0.1

            A         B         C         D         E
1    0.227207  0.623822  0.604859  0.271279  0.048137
4    0.181373  0.565818  0.765258  0.486793  0.556033
8    0.077306  0.255906  0.119884  0.887467  0.170566
13    0.15554  0.127012  0.623199  0.979875  0.854275
16   0.120144  0.268233  0.917198  0.340145  0.238116
..        ...       ...       ...       ...       ...
326  0.155612  0.788812  0.256840  0.638890  0.968106
327  0.085294  0.241955  0.383340  0.515506  0.264251
334  0.022893  0.633575  0.451925  0.497557  0.262580
336  0.229567  0.560952  0.601893  0.405042  0.352048
338  0.066956  0.418104  0.807854  0.516967  0.161808

[89 rows x 5 columns]

In [43]:
new_pd.loc[ : , ['C','D']]

            C         D
0    0.109810  0.284877
1    0.604859  0.271279
2    0.793529  0.381459
3    0.354690  0.910700
4    0.765258  0.486793
..        ...       ...
336  0.601893  0.405042
337  0.667149  0.846669
338  0.807854  0.516967
339  0.362530  0.472115
340  0.225201  0.796738

[341 rows x 2 columns]

In [44]:
new_pd.loc[[1,2,3] , : ]

          A         B         C         D         E
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608

In [45]:
new_pd.head()

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [46]:
new_pd.iloc[0,4]
# 0 th Row and 4 th Column

0.24931935605039746

In [47]:
new_pd.iloc[[0,4],[1,3]]

          B         D
0  0.750974  0.284877
4  0.565818  0.486793

In [48]:
new_pd.head()

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033

In [49]:
new_pd.drop([0])
# for Rows delet

            A         B         C         D         E
1    0.227207  0.623822  0.604859  0.271279  0.048137
2    0.316193  0.959645  0.793529  0.381459  0.247616
3     0.88419  0.242041  0.354690  0.910700  0.881608
4    0.181373  0.565818  0.765258  0.486793  0.556033
5     0.82903  0.865788  0.741317  0.646047  0.927460
..        ...       ...       ...       ...       ...
336  0.229567  0.560952  0.601893  0.405042  0.352048
337  0.792553  0.251601  0.667149  0.846669  0.199375
338  0.066956  0.418104  0.807854  0.516967  0.161808
339  0.648442  0.917726  0.362530  0.472115  0.333250
340  0.395942  0.286154  0.225201  0.796738  0.103381

[340 rows x 5 columns]

In [50]:
new_pd.drop(['A','E'], axis=1)

            B         C         D
0    0.750974  0.109810  0.284877
1    0.623822  0.604859  0.271279
2    0.959645  0.793529  0.381459
3    0.242041  0.354690  0.910700
4    0.565818  0.765258  0.486793
..        ...       ...       ...
336  0.560952  0.601893  0.405042
337  0.251601  0.667149  0.846669
338  0.418104  0.807854  0.516967
339  0.917726  0.362530  0.472115
340  0.286154  0.225201  0.796738

[341 rows x 3 columns]

In [51]:
new_pd.drop([1,5] , axis=0)

            A         B         C         D         E
0         454  0.750974  0.109810  0.284877  0.249319
2    0.316193  0.959645  0.793529  0.381459  0.247616
3     0.88419  0.242041  0.354690  0.910700  0.881608
4    0.181373  0.565818  0.765258  0.486793  0.556033
6    0.863096  0.729849  0.112545  0.805845  0.772910
..        ...       ...       ...       ...       ...
336  0.229567  0.560952  0.601893  0.405042  0.352048
337  0.792553  0.251601  0.667149  0.846669  0.199375
338  0.066956  0.418104  0.807854  0.516967  0.161808
339  0.648442  0.917726  0.362530  0.472115  0.333250
340  0.395942  0.286154  0.225201  0.796738  0.103381

[339 rows x 5 columns]

In [52]:
new_pd.head(10)

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.227207  0.623822  0.604859  0.271279  0.048137
2  0.316193  0.959645  0.793529  0.381459  0.247616
3   0.88419  0.242041  0.354690  0.910700  0.881608
4  0.181373  0.565818  0.765258  0.486793  0.556033
5   0.82903  0.865788  0.741317  0.646047  0.927460
6  0.863096  0.729849  0.112545  0.805845  0.772910
7  0.464964  0.735983  0.015067  0.338418  0.834068
8  0.077306  0.255906  0.119884  0.887467  0.170566
9  0.923632  0.448117  0.129855  0.128947  0.939418

In [53]:
new_pd.drop([1,5] , axis=0 , inplace=True)

In [54]:
new_pd.head(10)

           A         B         C         D         E
0        454  0.750974  0.109810  0.284877  0.249319
2   0.316193  0.959645  0.793529  0.381459  0.247616
3    0.88419  0.242041  0.354690  0.910700  0.881608
4   0.181373  0.565818  0.765258  0.486793  0.556033
6   0.863096  0.729849  0.112545  0.805845  0.772910
7   0.464964  0.735983  0.015067  0.338418  0.834068
8   0.077306  0.255906  0.119884  0.887467  0.170566
9   0.923632  0.448117  0.129855  0.128947  0.939418
10  0.378439  0.649081  0.415529  0.678249  0.171714
11   0.81633  0.401348  0.155989  0.803041  0.037865

In [55]:
new_pd.reset_index(drop=True , inplace=True)

In [56]:
new_pd.head(10)

          A         B         C         D         E
0       454  0.750974  0.109810  0.284877  0.249319
1  0.316193  0.959645  0.793529  0.381459  0.247616
2   0.88419  0.242041  0.354690  0.910700  0.881608
3  0.181373  0.565818  0.765258  0.486793  0.556033
4  0.863096  0.729849  0.112545  0.805845  0.772910
5  0.464964  0.735983  0.015067  0.338418  0.834068
6  0.077306  0.255906  0.119884  0.887467  0.170566
7  0.923632  0.448117  0.129855  0.128947  0.939418
8  0.378439  0.649081  0.415529  0.678249  0.171714
9   0.81633  0.401348  0.155989  0.803041  0.037865

In [57]:
new_pd['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
334    False
335    False
336    False
337    False
338    False
Name: B, Length: 339, dtype: bool

In [58]:
new_pd['B'] = None

In [59]:
new_pd['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
334    True
335    True
336    True
337    True
338    True
Name: B, Length: 339, dtype: bool

In [60]:
new_pd

            A     B         C         D         E
0         454  None  0.109810  0.284877  0.249319
1    0.316193  None  0.793529  0.381459  0.247616
2     0.88419  None  0.354690  0.910700  0.881608
3    0.181373  None  0.765258  0.486793  0.556033
4    0.863096  None  0.112545  0.805845  0.772910
..        ...   ...       ...       ...       ...
334  0.229567  None  0.601893  0.405042  0.352048
335  0.792553  None  0.667149  0.846669  0.199375
336  0.066956  None  0.807854  0.516967  0.161808
337  0.648442  None  0.362530  0.472115  0.333250
338  0.395942  None  0.225201  0.796738  0.103381

[339 rows x 5 columns]

In [61]:
new_pd.loc[ : , ['C']] = None

In [62]:
new_pd

            A     B     C         D         E
0         454  None  None  0.284877  0.249319
1    0.316193  None  None  0.381459  0.247616
2     0.88419  None  None  0.910700  0.881608
3    0.181373  None  None  0.486793  0.556033
4    0.863096  None  None  0.805845  0.772910
..        ...   ...   ...       ...       ...
334  0.229567  None  None  0.405042  0.352048
335  0.792553  None  None  0.846669  0.199375
336  0.066956  None  None  0.516967  0.161808
337  0.648442  None  None  0.472115  0.333250
338  0.395942  None  None  0.796738  0.103381

[339 rows x 5 columns]

In [63]:
new_pd.loc[ : , ['C']] = 452

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19780\1443282069.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  new_pd.loc[ : , ['C']] = 452

In [64]:
new_pd

            A     B    C         D         E
0         454  None  452  0.284877  0.249319
1    0.316193  None  452  0.381459  0.247616
2     0.88419  None  452  0.910700  0.881608
3    0.181373  None  452  0.486793  0.556033
4    0.863096  None  452  0.805845  0.772910
..        ...   ...  ...       ...       ...
334  0.229567  None  452  0.405042  0.352048
335  0.792553  None  452  0.846669  0.199375
336  0.066956  None  452  0.516967  0.161808
337  0.648442  None  452  0.472115  0.333250
338  0.395942  None  452  0.796738  0.103381

[339 rows x 5 columns]

In [65]:
new_pd['C'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
334    False
335    False
336    False
337    False
338    False
Name: C, Length: 339, dtype: bool

In [66]:
new_pd.head(10)

          A     B    C         D         E
0       454  None  452  0.284877  0.249319
1  0.316193  None  452  0.381459  0.247616
2   0.88419  None  452  0.910700  0.881608
3  0.181373  None  452  0.486793  0.556033
4  0.863096  None  452  0.805845  0.772910
5  0.464964  None  452  0.338418  0.834068
6  0.077306  None  452  0.887467  0.170566
7  0.923632  None  452  0.128947  0.939418
8  0.378439  None  452  0.678249  0.171714
9   0.81633  None  452  0.803041  0.037865

In [67]:
data = pd.DataFrame({'Name' : ['Sushil','Roshan','RSP',pd.NaT,'Lucifer'],
                     'Contry' : ['India','Russia','Japan','India',np.nan]})
data

      Name  Contry
0   Sushil   India
1   Roshan  Russia
2      RSP   Japan
3      NaT   India
4  Lucifer     NaN

In [68]:
data.index = np.arange(1,6)

In [69]:
data

      Name  Contry
1   Sushil   India
2   Roshan  Russia
3      RSP   Japan
4      NaT   India
5  Lucifer     NaN

In [70]:
data.dropna()

     Name  Contry
1  Sushil   India
2  Roshan  Russia
3     RSP   Japan

if we use

data.dropna(how = 'all',axis = 1)

then the all column which have all elements are na they are remove

In [71]:
data.drop_duplicates(subset=['Contry'])

      Name  Contry
1   Sushil   India
2   Roshan  Russia
3      RSP   Japan
5  Lucifer     NaN

In [72]:
data.drop_duplicates(subset=['Contry'] , keep='last')

      Name  Contry
2   Roshan  Russia
3      RSP   Japan
4      NaT   India
5  Lucifer     NaN

In [73]:
data.drop_duplicates(subset=['Contry'] , keep=False)

      Name  Contry
2   Roshan  Russia
3      RSP   Japan
5  Lucifer     NaN

In [74]:
data.shape

(5, 2)

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 1 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Contry  4 non-null      object
dtypes: object(2)
memory usage: 120.0+ bytes

In [76]:
data['Contry'].values

array(['India', 'Russia', 'Japan', 'India', nan], dtype=object)

In [77]:
data['Contry'].value_counts()
# NaN is not count

India     2
Russia    1
Japan     1
Name: Contry, dtype: int64

In [78]:
data['Contry'].value_counts(dropna=False)
# with the dropna = False NaN also count

India     2
Russia    1
Japan     1
NaN       1
Name: Contry, dtype: int64

In [79]:
data.isnull()

    Name  Contry
1  False   False
2  False   False
3  False   False
4   True   False
5  False    True

In [80]:
data.notnull()

    Name  Contry
1   True    True
2   True    True
3   True    True
4  False    True
5   True   False

In [81]:
data

      Name  Contry
1   Sushil   India
2   Roshan  Russia
3      RSP   Japan
4      NaT   India
5  Lucifer     NaN